-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, sum(p.PRICE * o.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT p left join FOOD_ORDER o
on p.PRODUCT_ID = o.PRODUCT_ID
where o.PRODUCE_DATE >= '2022-05-01' and o.PRODUCE_DATE <= '2022-05-31'
group by p.PRODUCT_ID
order by TOTAL_SALES desc, PRODUCT_ID;